<?php

namespace Yeargle\Bundle\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SearchesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SearchesRepository extends EntityRepository
{

}
